version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}
    mongo_data: {}

services:
  automata:
    image: muncs/automata
    restart: always
    volumes:
      - ./mounted_plugins:/app/mounted_plugins
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mvertes/alpine-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: always
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    expose:
      - 3000
    networks:
      - web
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: stats.muncompsci.ca"
      traefik.port: 3000
      traefik.frontend.entryPoints: "https"

networks:
  web:
    external: true
