version: '3'

services:
  automata:
    build: muncs/automata
    restart: always
    volumes:
      - ./mounted_plugins:/app/mounted_plugins
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mvertes/alpine-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
